# Adapted from asm64-hooligan/cmpunlocker: prefer the patched driver over DKMS.
override nvidia * updates/cmpunlocker
override nvidia-modeset * updates/cmpunlocker
override nvidia-uvm * updates/cmpunlocker
override nvidia-drm * updates/cmpunlocker
override nvidia-peermem * updates/cmpunlocker
